"""Optional, filesystem-only Obsidian vault projection adapter.

The vault is a human-readable projection of operator state, not its execution
database.  This module therefore stays useful when Obsidian is not installed:
the adapter reports itself as disabled and projection calls become explicit
no-ops.  A path can be configured later without rebuilding the application.
"""

from __future__ import annotations

import json
import os
import re
import tempfile
import unicodedata
from collections.abc import Mapping, Sequence
from dataclasses import dataclass
from datetime import date, datetime
from pathlib import Path, PureWindowsPath
from typing import Any

from .base import AdapterHealth, AdapterUnavailableError, UnsafePathError


DEFAULT_ENV_KEYS: tuple[str, ...] = (
    "HERMES_OPERATOR_OBSIDIAN_VAULT",
    "OBSIDIAN_VAULT_PATH",
)

_FRONTMATTER_KEY = re.compile(r"^([A-Za-z_][A-Za-z0-9_-]*):(?:[ \t]*(.*))?$")


@dataclass(frozen=True, slots=True)
class ProjectionResult:
    """Outcome of one optional vault projection."""

    enabled: bool
    path: Path | None = None
    created: bool = False
    updated: bool = False
    reason: str | None = None

    @property
    def changed(self) -> bool:
        return self.created or self.updated


@dataclass(frozen=True, slots=True)
class VaultDocument:
    """A parsed Markdown document from the configured vault."""

    path: Path
    frontmatter: Mapping[str, Any]
    body: str
    raw: str


def _default_candidates() -> tuple[Path, ...]:
    home = Path.home()
    return (
        home / "Documents" / "Obsidian",
        home / "Obsidian",
        home
        / "Library"
        / "Mobile Documents"
        / "iCloud~md~obsidian"
        / "Documents",
    )


def _expand_candidate(value: str | os.PathLike[str]) -> Path:
    return Path(os.path.expandvars(os.fspath(value))).expanduser()


def _vault_at_or_below(candidate: Path) -> Path | None:
    """Return an exact vault or the sole marked vault directly below it."""

    if not candidate.is_dir():
        return None
    if (candidate / ".obsidian").is_dir():
        return candidate.resolve()
    try:
        marked_children = sorted(
            child.resolve()
            for child in candidate.iterdir()
            if child.is_dir() and (child / ".obsidian").is_dir()
        )
    except OSError:
        return None
    # Never guess when a common Obsidian root contains multiple vaults.
    return marked_children[0] if len(marked_children) == 1 else None


def discover_vault(
    vault_path: str | os.PathLike[str] | None = None,
    *,
    candidates: Sequence[str | os.PathLike[str]] = (),
    env: Mapping[str, str] | None = None,
    env_keys: Sequence[str] = DEFAULT_ENV_KEYS,
    include_defaults: bool = True,
) -> Path | None:
    """Discover a vault conservatively without creating filesystem state.

    An explicit or environment-provided directory is accepted even before it
    has an ``.obsidian`` marker.  Generic discovery candidates require either
    the marker or exactly one marked direct child, preventing an arbitrary
    documents directory from being selected as the vault.
    """

    if vault_path is not None:
        explicit = _expand_candidate(vault_path)
        return explicit.resolve() if explicit.is_dir() else None

    environment = os.environ if env is None else env
    for key in env_keys:
        configured = environment.get(key)
        if configured:
            path = _expand_candidate(configured)
            if path.is_dir():
                return path.resolve()

    search = [_expand_candidate(candidate) for candidate in candidates]
    if include_defaults:
        search.extend(_default_candidates())
    for candidate in search:
        discovered = _vault_at_or_below(candidate)
        if discovered is not None:
            return discovered
    return None


def split_frontmatter(markdown: str) -> tuple[str | None, str]:
    """Split a Markdown string into raw YAML frontmatter and body."""

    lines = markdown.splitlines(keepends=True)
    if not lines or lines[0].strip() != "---":
        return None, markdown
    for index in range(1, len(lines)):
        if lines[index].strip() == "---":
            return "".join(lines[1:index]), "".join(lines[index + 1 :])
    return None, markdown


def _parse_scalar(value: str) -> Any:
    value = value.strip()
    if not value:
        return ""
    try:
        return json.loads(value)
    except json.JSONDecodeError:
        lowered = value.lower()
        if lowered in {"null", "~"}:
            return None
        if lowered in {"true", "false"}:
            return lowered == "true"
        return value


def parse_frontmatter(header: str | None) -> dict[str, Any]:
    """Parse scalar and JSON-flow fields generated by this adapter.

    Complex hand-authored YAML blocks remain available in the raw document and
    are preserved by updates, even when this lightweight parser cannot turn
    them into Python values.
    """

    if header is None:
        return {}
    parsed: dict[str, Any] = {}
    lines = header.splitlines()
    index = 0
    while index < len(lines):
        match = _FRONTMATTER_KEY.match(lines[index])
        if not match:
            index += 1
            continue
        key, scalar = match.groups()
        if scalar:
            parsed[key] = _parse_scalar(scalar)
            index += 1
            continue
        block: list[str] = []
        index += 1
        while index < len(lines) and not _FRONTMATTER_KEY.match(lines[index]):
            block.append(lines[index])
            index += 1
        parsed[key] = "\n".join(block).rstrip() if block else ""
    return parsed


def _top_level_blocks(header: str | None) -> list[tuple[str | None, list[str]]]:
    if not header:
        return []
    blocks: list[tuple[str | None, list[str]]] = []
    current_key: str | None = None
    current_lines: list[str] = []
    for line in header.splitlines():
        match = _FRONTMATTER_KEY.match(line)
        if match:
            if current_lines:
                blocks.append((current_key, current_lines))
            current_key = match.group(1)
            current_lines = [line]
        else:
            current_lines.append(line)
    if current_lines:
        blocks.append((current_key, current_lines))
    return blocks


def _json_default(value: object) -> str:
    if isinstance(value, (date, datetime)):
        return value.isoformat()
    if isinstance(value, os.PathLike):
        return os.fspath(value)
    return str(value)


def _frontmatter_line(key: str, value: Any) -> str:
    if not _FRONTMATTER_KEY.match(f"{key}:"):
        raise ValueError(f"Invalid frontmatter key: {key!r}")
    rendered = json.dumps(
        value,
        ensure_ascii=False,
        separators=(",", ":"),
        sort_keys=isinstance(value, Mapping),
        default=_json_default,
    )
    return f"{key}: {rendered}"


def merge_frontmatter(header: str | None, updates: Mapping[str, Any]) -> str:
    """Merge fields while retaining unowned, potentially complex YAML blocks."""

    remaining = dict(updates)
    output: list[str] = []
    seen: set[str] = set()
    for key, lines in _top_level_blocks(header):
        if key is None:
            output.extend(lines)
        elif key in remaining:
            if key not in seen:
                output.append(_frontmatter_line(key, remaining.pop(key)))
                seen.add(key)
        else:
            output.extend(lines)
    for key, value in remaining.items():
        output.append(_frontmatter_line(str(key), value))
    return "\n".join(output).strip("\n")


def _slug(value: object, *, fallback: str) -> str:
    normalized = unicodedata.normalize("NFKD", str(value))
    ascii_value = normalized.encode("ascii", "ignore").decode("ascii").lower()
    slug = re.sub(r"[^a-z0-9]+", "-", ascii_value).strip("-")
    return (slug or fallback)[:120].rstrip("-")


def _managed_body(existing: str, kind: str, body: str) -> str:
    start = f"<!-- hermes-operator:{kind}:start -->"
    end = f"<!-- hermes-operator:{kind}:end -->"
    # Source material cannot terminate the managed region early.
    safe_body = body.replace(start, "[managed marker removed]").replace(
        end, "[managed marker removed]"
    )
    managed = f"{start}\n{safe_body.rstrip()}\n{end}\n"
    pattern = re.compile(re.escape(start) + r".*?" + re.escape(end) + r"\n?", re.DOTALL)
    if pattern.search(existing):
        return pattern.sub(managed, existing, count=1)
    if not existing:
        return managed
    return existing.rstrip() + "\n\n" + managed


class ObsidianAdapter:
    """Project structured operator records into an optional Obsidian vault."""

    def __init__(
        self,
        vault_path: str | os.PathLike[str] | None = None,
        *,
        candidates: Sequence[str | os.PathLike[str]] = (),
        env: Mapping[str, str] | None = None,
        env_keys: Sequence[str] = DEFAULT_ENV_KEYS,
        include_default_candidates: bool = True,
        create: bool = False,
    ) -> None:
        self.vault_path: Path | None = None
        self.disabled_reason: str | None = None

        if vault_path is not None and create:
            requested = _expand_candidate(vault_path)
            requested.mkdir(parents=True, exist_ok=True)
        discovered = discover_vault(
            vault_path,
            candidates=candidates,
            env=env,
            env_keys=env_keys,
            include_defaults=include_default_candidates,
        )
        if discovered is None:
            self.disabled_reason = "No Obsidian vault is configured"
        else:
            self.vault_path = discovered

    @property
    def enabled(self) -> bool:
        return self.vault_path is not None

    def configure(
        self, vault_path: str | os.PathLike[str], *, create: bool = False
    ) -> bool:
        """Configure or replace the vault path after service startup."""

        requested = _expand_candidate(vault_path)
        if create:
            requested.mkdir(parents=True, exist_ok=True)
        if not requested.is_dir():
            self.vault_path = None
            self.disabled_reason = f"Vault path is not a directory: {requested}"
            return False
        self.vault_path = requested.resolve()
        self.disabled_reason = None
        return True

    def disable(self, reason: str = "Obsidian integration was disabled") -> None:
        self.vault_path = None
        self.disabled_reason = reason

    def health(self) -> AdapterHealth:
        if self.vault_path is None:
            return AdapterHealth(
                enabled=False,
                available=False,
                detail=self.disabled_reason or "No Obsidian vault is configured",
            )
        available = self.vault_path.is_dir() and os.access(self.vault_path, os.R_OK)
        writable = available and os.access(self.vault_path, os.W_OK)
        return AdapterHealth(
            enabled=True,
            available=bool(available and writable),
            detail=(
                "Obsidian vault is readable and writable"
                if available and writable
                else "Obsidian vault is not readable and writable"
            ),
            capabilities=("read", "project") if available and writable else (),
        )

    def resolve_path(self, relative_path: str | os.PathLike[str]) -> Path:
        """Resolve a relative note path and prove it remains inside the vault."""

        if self.vault_path is None:
            raise AdapterUnavailableError(
                self.disabled_reason or "No Obsidian vault is configured"
            )
        raw = os.fspath(relative_path)
        path = Path(raw)
        if not raw or path.is_absolute() or PureWindowsPath(raw).is_absolute():
            raise UnsafePathError("Vault note path must be relative")
        if any(part == ".." for part in path.parts):
            raise UnsafePathError("Vault note path cannot contain parent traversal")

        root = self.vault_path.resolve()
        target = (root / path).resolve(strict=False)
        try:
            target.relative_to(root)
        except ValueError as exc:
            raise UnsafePathError("Vault note path escapes the configured vault") from exc
        if target == root:
            raise UnsafePathError("Vault note path must identify a file")
        return target

    def read_document(self, relative_path: str | os.PathLike[str]) -> VaultDocument | None:
        if not self.enabled:
            return None
        path = self.resolve_path(relative_path)
        if not path.is_file():
            return None
        raw = path.read_text(encoding="utf-8")
        header, body = split_frontmatter(raw)
        return VaultDocument(
            path=path,
            frontmatter=parse_frontmatter(header),
            body=body,
            raw=raw,
        )

    def list_documents(
        self,
        relative_directory: str | os.PathLike[str],
        *,
        limit: int = 100,
        max_bytes: int = 131_072,
    ) -> list[VaultDocument]:
        """Read bounded direct Markdown children of one vault directory.

        Both the directory scan and total bytes read are capped. Symlinked
        directories and files are ignored so a synced or plugin-managed vault
        cannot redirect this reader to another location.
        """

        if limit < 1 or max_bytes < 1:
            raise ValueError("Document list limits must be positive")
        if self.vault_path is None:
            return []

        raw = os.fspath(relative_directory)
        relative = Path(raw)
        if not raw or relative.is_absolute() or PureWindowsPath(raw).is_absolute():
            raise UnsafePathError("Vault directory path must be relative")
        if any(part == ".." for part in relative.parts):
            raise UnsafePathError("Vault directory path cannot contain parent traversal")
        unresolved = self.vault_path / relative
        current = self.vault_path
        for part in relative.parts:
            current = current / part
            if current.is_symlink():
                return []
        directory = self.resolve_path(relative)
        if not directory.is_dir():
            return []

        # Do not let a directory with an arbitrary number of irrelevant files
        # turn a recovery tick into an unbounded filesystem walk.
        scan_limit = max(256, limit * 4)
        candidates: list[os.DirEntry[str]] = []
        try:
            with os.scandir(directory) as entries:
                for index, entry in enumerate(entries):
                    if index >= scan_limit:
                        break
                    if entry.name.lower().endswith(".md"):
                        candidates.append(entry)
        except OSError:
            return []

        documents: list[VaultDocument] = []
        total_bytes = 0
        for entry in sorted(candidates, key=lambda item: item.name.casefold()):
            if len(documents) >= limit or total_bytes >= max_bytes:
                break
            try:
                if entry.is_symlink() or not entry.is_file(follow_symlinks=False):
                    continue
                stat_result = entry.stat(follow_symlinks=False)
            except OSError:
                continue
            remaining = max_bytes - total_bytes
            if stat_result.st_size > remaining:
                continue
            flags = os.O_RDONLY
            if hasattr(os, "O_NOFOLLOW"):
                flags |= os.O_NOFOLLOW
            try:
                descriptor = os.open(entry.path, flags)
                with os.fdopen(descriptor, "rb") as handle:
                    encoded = handle.read(remaining + 1)
            except (OSError, ValueError):
                continue
            if len(encoded) > remaining:
                continue
            try:
                raw_document = encoded.decode("utf-8")
            except UnicodeDecodeError:
                continue
            total_bytes += len(encoded)
            header, body = split_frontmatter(raw_document)
            documents.append(
                VaultDocument(
                    path=directory / entry.name,
                    frontmatter=parse_frontmatter(header),
                    body=body,
                    raw=raw_document,
                )
            )
        return documents

    def project_project(
        self,
        project: Mapping[str, Any],
        *,
        body: str | None = None,
        relative_path: str | os.PathLike[str] | None = None,
    ) -> ProjectionResult:
        identifier = project.get("id") or project.get("project_id") or project.get("title")
        path = relative_path or f"Projects/{_slug(identifier or 'project', fallback='project')}.md"
        return self._project("project", project, path, body)

    def project_event(
        self,
        event: Mapping[str, Any],
        *,
        body: str | None = None,
        relative_path: str | os.PathLike[str] | None = None,
    ) -> ProjectionResult:
        identifier = event.get("id") or event.get("event_id") or event.get("title")
        timestamp = (
            event.get("occurred_at")
            or event.get("timestamp")
            or event.get("start_at")
            or ""
        )
        match = re.match(r"\d{4}-\d{2}-\d{2}", str(timestamp))
        prefix = f"{match.group(0)}-" if match else ""
        path = relative_path or (
            f"Events/{prefix}{_slug(identifier or 'event', fallback='event')}.md"
        )
        return self._project("event", event, path, body)

    def project_note(
        self,
        note: Mapping[str, Any],
        *,
        body: str | None = None,
        relative_path: str | os.PathLike[str] | None = None,
    ) -> ProjectionResult:
        identifier = note.get("id") or note.get("note_id") or note.get("title")
        path = relative_path or f"Notes/{_slug(identifier or 'note', fallback='note')}.md"
        return self._project("note", note, path, body)

    # More natural aliases for callers that treat projections as upserts.
    upsert_project = project_project
    record_event = project_event
    upsert_note = project_note

    def _project(
        self,
        kind: str,
        record: Mapping[str, Any],
        relative_path: str | os.PathLike[str],
        body: str | None,
    ) -> ProjectionResult:
        if self.vault_path is None:
            return ProjectionResult(
                enabled=False,
                reason=self.disabled_reason or "No Obsidian vault is configured",
            )

        target = self.resolve_path(relative_path)
        if target.suffix.lower() != ".md":
            raise UnsafePathError("Vault projection path must end in .md")
        if target.exists() and not target.is_file():
            raise UnsafePathError("Vault projection path must identify a regular file")
        existed = target.exists()
        existing = target.read_text(encoding="utf-8") if target.is_file() else ""
        old_header, old_body = split_frontmatter(existing)

        explicit_frontmatter = record.get("frontmatter", {})
        if explicit_frontmatter and not isinstance(explicit_frontmatter, Mapping):
            raise ValueError("record.frontmatter must be a mapping")
        fields = {
            str(key): value
            for key, value in record.items()
            if key not in {"body", "content", "frontmatter"}
        }
        fields.update(dict(explicit_frontmatter))
        # The projection type is adapter-owned and cannot be overridden by a
        # record or caller-provided frontmatter.
        fields = {**fields, "kind": kind}

        title = str(record.get("title") or record.get("name") or kind.title())
        managed_content = body
        if managed_content is None:
            supplied = record.get("content") or record.get("body") or record.get("summary")
            managed_content = f"# {title}"
            if supplied:
                managed_content += f"\n\n{supplied}"

        new_header = merge_frontmatter(old_header, fields)
        new_body = _managed_body(old_body, kind, str(managed_content))
        rendered = f"---\n{new_header}\n---\n{new_body}"
        if existing == rendered:
            return ProjectionResult(enabled=True, path=target)

        target.parent.mkdir(parents=True, exist_ok=True)
        # Re-resolve after mkdir so a pre-existing symlinked parent cannot be
        # used to escape containment between validation and the write.
        if self.resolve_path(relative_path) != target:
            raise UnsafePathError("Vault projection path changed during write")
        self._atomic_write(target, rendered)
        return ProjectionResult(
            enabled=True,
            path=target,
            created=not existed,
            updated=existed,
        )

    @staticmethod
    def _atomic_write(path: Path, content: str) -> None:
        descriptor, temporary_name = tempfile.mkstemp(
            prefix=f".{path.name}.", suffix=".tmp", dir=path.parent
        )
        try:
            with os.fdopen(descriptor, "w", encoding="utf-8", newline="\n") as handle:
                handle.write(content)
                handle.flush()
                os.fsync(handle.fileno())
            os.replace(temporary_name, path)
        except BaseException:
            try:
                os.unlink(temporary_name)
            except FileNotFoundError:
                pass
            raise
